MYSQL_URI : localhost:3306
MYSQL_DATABASE: elotus
MYSQL_USERNAME: elotus
MYSQL_PASSWORD: elotus
MYSQL_MAX_CONNECTION: "1"
AUTHEN_SERVER_PORT: "8080"
UPLOAD_SERVER_PORT: "8081"
SERVER_MODE: debug
JWT_SECRET_KEY: toilaken
JWT_REFRESH_SECRET_KEY: refresh_toilaken